[project]
name = "re-tts"
version = "0.3.6_Alpha20260902"
description = "A Simple TTS tool based on RVC 2.2.231006 and edge-tts"
readme = "README.md"
authors = [
    { name = "Kaning123", email = "kaning123official@163.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.5.0",
    "edge-tts>=7.2.8",
    "langdetect>=1.0.9",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "rpyc>=6.0.2",
    "tqdm>=4.70.0",
]

[project.scripts]
re-tts = "re_tts:main"
rvc-webui-boot = "re_tts:boot_webui"
[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"
